### PR TITLE
implementing openTCPServerSocketWithOptions to not forget "listen"

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
Should fix https://github.com/kazu-yamamoto/http2-tls/pull/17.

### CODE REVIEW

**Comment by edsko** [comment]
@kazu-yamamoto Yes, this works for me (alongside https://github.com/kazu-yamamoto/http2-tls/commit/6ecea0f22a576c3f0dcbb9efd7a402919bf4ad10). Thanks! :)

**Comment by kazu-yamamoto** [comment]
Merged. Thanks!

**Comment by kazu-yamamoto** [comment]
v0.4.0 has been released.

**Comment by edsko** [comment]
Thanks @kazu-yamamoto !

**Pull request merged**
